import type { Metadata } from "next";
import '@/app/globals.css'
import NavBar from '@/components/public/Navbar'
import Footer from "@/components/public/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="fr">
      <body className={`antialiased`}>
        <NavBar />
          <main>
            {children}
          </main>
        <Footer />
      </body>
    </html>
  );
}
